---

role_description: |
  Enrolls a Linux host into a Microsoft Active Directory Domain using Kerberos

role_vars_fields:
  - name: variable
    width: 10
  - name: required
    width: 5
  - name: type
    width: 5
  - name: default
    width: 40
  - name: platform
    width: 40
  - name: description
    width: 40

role_vars:
  - variable: adjoin_command
    required: no
    type: string
    default: realm
    platform: all
    description: Command to use for joining AD
  - variable: adjoin_spn
    required: no
    type: list
    default: 
      - nfs
      - cifs
    platform: all
    description: Kerberos Service Principal Name (SPN) to create
  - variable: ad_tls
    required: no
    type: boolean
    default: true
    platform: all
    description: Configure AD connection using SSL/TLS
  - variable: ad_leave
    required: no
    type: boolean
    default: false
    platform: all
    description:  Leave the AD realm before joining it
  - variable: ad_ldap_id_mapping
    required: no
    type: boolean
    default: true
    platform: all
    description: Use AD provided UID/GID
  - variable: adjoin_packages
    required: no
    type: list
    default: 
      - realmd
      - libnss-sss
      - libpam-sss
      - sssd
      - sssd-tools
      - adcli
      - samba-common-bin
      - oddjob
      - oddjob-mkhomedir
      - packagekit
      - krb5-user
    platform: family-Debian
    description:
  - variable: adjoin_packages
    required: no
    type: list
    default: 
      - sssd
      - realmd
      - oddjob
      - oddjob-mkhomedir
      - adcli
      - samba-common
      - krb5-workstation
      - openldap-clients
    platform: family-RedHat-7
    description:
  - variable: adjoin_packages
    required: no
    type: list
    default: 
      - sssd
      - realmd
      - oddjob
      - oddjob-mkhomedir
      - adcli
      - samba-common
      - krb5-workstation
      - openldap-clients
    platform: family-RedHat-8
    description:

role_examples:
  - description: |
    code: |-
      - hosts: all
        roles:
          - {{ role }}
