---

- name: Configure sssd
  ansible.builtin.template:
    src: "{{ adjoin_sssd_template }}"
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root
    mode: '0600'
    backup: yes
  notify: Restart sssd
