---

- name: Get list of all realms
  ansible.builtin.command: realm list
  changed_when: false
  check_mode: false
  register: _realm_check

- name: Leave AD realm
  ansible.builtin.command: realm leave {{ ad_realm }}
  changed_when: true
  when:
    - ad_leave | bool
    - _realm_check.stdout is search(ad_realm)

- name: Get list of all realms
  ansible.builtin.command: realm list
  changed_when: false
  check_mode: false
  register: _realm_check

- name: Enroll into AD if not enrolled yet  # noqa no-free-form
  ansible.builtin.shell: |
    set -o pipefail
    exec > /tmp/adcli.log 2>&1
    echo "{{ ad_password }}" | adcli join -v \
      --verbose {{ '--use-ldaps' if ad_tls|bool }} \
      --domain={{ ad_realm }} \
      --domain-controller={{ ad_servers | first }} \
      --domain-realm={{ ad_realm | upper }} \
      --computer-name={{ inventory_hostname }} \
      --host-fqdn={{ inventory_hostname }} \
      --login-user={{ ad_user }} \
      --stdin-password
  args:
    executable: /bin/bash
  changed_when: true
  when:
    - adjoin_command == 'adcli'
    - _realm_check.stdout is not search(ad_realm)
  tags:
    - molecule-notest

- name: Enroll into AD if not enrolled yet
  ansible.builtin.shell: |
    set -o pipefail
    exec > /tmp/realm.log 2>&1
    realm join -v {{ '--use-ldaps' if ad_tls|bool }} {{ ad_realm }}
  args:
    executable: /bin/bash
  changed_when: true
  when:
    - adjoin_command == 'realm'
    - _realm_check.stdout|length == 0
  tags:
    - molecule-notest
