---

- name: Get list of all realms
  ansible.builtin.command: realm list
  changed_when: false
  check_mode: false
  register: _realm_check

- name: Leave AD realm
  ansible.builtin.command: realm leave {{ adjoin_realm }}
  changed_when: true
  when:
    - adjoin_leave | bool
    - _realm_check.stdout is search(adjoin_realm)

- name: Get list of all realms
  ansible.builtin.command: realm list
  changed_when: false
  check_mode: false
  register: _realm_check

- name: Enroll into AD if not enrolled yet  # noqa no-free-form
  ansible.builtin.shell: |
    set -o pipefail
    exec > /tmp/adcli.log 2>&1
    echo "{{ adjoin_password }}" | adcli join -v \
      --verbose {{ '--use-ldaps' if adjoin_tls|bool }} \
      --domain={{ adjoin_realm }} \
      --domain-controller={{ adjoin_servers | first }} \
      --domain-realm={{ adjoin_realm | upper }} \
      --computer-name={{ inventory_hostname }} \
      --host-fqdn={{ inventory_hostname }} \
      --login-user={{ adjoin_user }} \
      --stdin-password
  args:
    executable: /bin/bash
  changed_when: true
  when:
    - adjoin_command == 'adcli'
    - _realm_check.stdout is not search(adjoin_realm)
  tags:
    - molecule-notest

- name: Enroll into AD if not enrolled yet
  ansible.builtin.shell: |
    set -o pipefail
    exec > /tmp/realm.log 2>&1
    realm join -v {{ '--use-ldaps' if adjoin_tls|bool }} {{ adjoin_realm }}
  args:
    executable: /bin/bash
  changed_when: true
  when:
    - adjoin_command == 'realm'
    - _realm_check.stdout|length == 0
  tags:
    - molecule-notest
