---

- name: Leave AD realm
  command: realm leave {{ ad_realm }}
  when: ad_leave|bool

- name: Test if enrolled into realm
  shell:
    realm list | awk 'NR==1'
  changed_when: false
  check_mode: false
  register: _realm_check

- name: Enroll into AD if not enrolled yet
  shell: |
    exec > /tmp/adcli.log 2>&1
    echo "{{ ad_password }}" | adcli join -v \
      --verbose {{ '--use-ldaps' if ad_tls|bool }} \
      --domain={{ ad_realm }} \
      --domain-controller={{ ad_servers | first }} \
      --domain-realm={{ ad_realm | upper }} \
      --computer-name={{ inventory_hostname }} \
      --host-fqdn={{ inventory_hostname }} \
      --login-user={{ ad_user }} \
      --stdin-password
  when:
    - adjoin_command == 'adcli'
    - _realm_check.stdout|length == 0

- name: Enroll into AD if not enrolled yet
  shell: |
    exec > /tmp/realm.log 2>&1
    realm join -v {{ '--use-ldaps' if ad_tls|bool }} {{ ad_realm }}
  when:
    - adjoin_command == 'realm'
    - _realm_check.stdout|length == 0
