---

- name: Configure kerberos (krb5)
  template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: Create krb5 conf directory
  file:
    path: /etc/krb5.conf.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Check for a valid kerberos ticket
  command: klist -s
  changed_when: false
  failed_when: false
  check_mode: false
  register: klist

- name: Obtain kerberos ticket
  shell: |
    set -o pipefail
    echo -n "{{ ad_password }}" | \ 
    kinit {{ ad_user }}@{{ ad_realm | upper }} && exit 1 || exit 2
  args:
    executable: /bin/bash
  register: _kinit
  changed_when: _kinit.rc == 1
  failed_when: _kinit.rc > 1
  when:
    - klist.rc != 0
    - molecule_test is undefined
