---

- name: Make sure all required variables are provided
  ansible.builtin.assert:
    that:
      - adjoin_realm is defined

- name: Test if running in molecule
  ansible.builtin.set_fact:
    molecule_running: "{{ True if (lookup('env', 'MOLECULE_FILE') | default('') | length) > 0 else False }}"

- name: Load variables based on OS type
  ansible.builtin.include_tasks:
    file: vars.yml

- name: Include all tasks
  ansible.builtin.include_tasks:
    file: "{{ item }}"
  loop:
    - install.yml
    - configure-kerberos.yml
    - configure-pam.yml
    - configure-ad.yml
    - configure-sssd.yml
    - spn.yml
