---

- name: Add AD server to inventory
  ansible.builtin.add_host:
    hostname: "{{ adjoin_server }}"
    ansible_host: "{{ adjoin_server }}"
    ansible_user: "{{ adjoin_user }}"
    ansible_password: "{{ adjoin_password }}"
    ansible_connection: winrm
    ansible_winrm_scheme: http
    ansible_port: 5985
  changed_when: false

- name: Check for NFS service principal with AD
  ansible.windows.win_shell: |
    setspn -L {{ inventory_hostname }}
  changed_when: false
  check_mode: no
  become: false
  register: _setspn
  delegate_to: "{{ adjoin_server }}"

- name: Register NFS service principal with AD
  ansible.windows.win_shell: |
    setspn -S nfs/{{ inventory_hostname }}.{{ adjoin_realm }} {{ inventory_hostname }}
  become: false
  when: _setspn is not search('nfs/'+inventory_hostname)
  delegate_to: "{{ adjoin_server }}"
