---
- name: Make dure all required variables ar provided
  ansible.builtin.assert:
    that:
      - adjoin_spn is defined

- name: Add SPN
  ansible.builtin.shell: |
    set -o pipefail
    if klist -k | grep -q "{{ spn }}/{{ inventory_hostname }}.{{ adjoin_realm }}"
    then
      exit 0
    else
      exec > /tmp/adcli.log 2>&1
      adcli update -C --add-service-principal {{ spn }}/{{ inventory_hostname }}.{{ adjoin_realm }} -v
      [[ $? -eq 0 ]] && exit 1 || exit 2
    fi
  args:
    executable: /bin/bash
  register: _adcli
  changed_when: _adcli.rc == 1
  failed_when: _adcli.rc > 1
  loop: "{{ adjoin_spn }}"
  loop_control:
    loop_var: spn
  tags:
    - molecule-notest
