---

- name: Converge
  hosts: all
  vars:
    molecule_running: "{{ true if (lookup('env', 'MOLECULE_FILE')|length)>0 else false }}"
    ad_realm: example.com
    ad_user: test
    ad_password: test
  tasks:
    - name: "Include role 'ansible-role-adjoin'"
      include_role:
        name: "ansible-role-adjoin"
