---

- name: Converge
  hosts: all
  vars:
    ad_realm: example.com
    ad_user: test
    ad_password: test
  tasks:
    - name: Include role 'ansible-role-adjoin'
      include_role:
        name: ansible-role-adjoin
