---

- name: Converge
  hosts: all
  become: "{{ molecule['converge']['become'] | default('yes') }}"
  vars:
    ad_password: test
    ad_realm: example.com
    ad_user: test
  tasks:
    - name: Include role 'ansible-role-adjoin'
      ansible.builtin.include_role:
        name: ansible-role-adjoin
