---

- name: Converge
  hosts: all
  become: "yes"
  vars:
    adjoin_password: test
    adjoin_realm: example.com
    adjoin_user: test
  tasks:
    - name: Include role 'ansible-role-adjoin'
      ansible.builtin.include_role:
        name: ansible-role-adjoin
